### ISSUE TITLE
which version node & npm used in project ?

### ISSUE THREAD

**Issue by todokku** [Hsins/Daily-GitHub-Trending#1]
hi Sean,
which version node & npm used in project ?

**Comment by Hsins** [comment]
Hi @todokku,

The versions of node and npm running on my local machine are:

- `node` v13.7.0
- `npm` 6.13.6

Besides, the GitHub Actions service is running with `node` v.13. Check the [workflows config file](https://github.com/Hsins/Daily-GitHub-Trending/blob/master/.github/workflows/daily-deploy.yml) for more information.
